runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:j0dZsvck6DGkp3thfuCd3aHSVBsGJrwRCXMw6xLzJtw=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie